
import java.text.MessageFormat;
import java.awt.*;
import javax.swing.*;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Nathan Liang
 */
public class JavaPOS extends javax.swing.JFrame {

    private final double taxRate = 0.08025;
    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    //===================================Functions=====================================================
    //This method calculates the total and tax
    public void itemCost(){
        double sum = 0;
        
        for(int i = 0; i < jTable1.getRowCount(); i++){
             sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        JTxtSubtotal.setText(Double.toString(sum));
        double cSubtotal = Double.parseDouble(JTxtSubtotal.getText());
        double cTax = (cSubtotal * this.taxRate);
        double cTotal = cSubtotal + cTax;
        String taxTotal = String.format("$ %.2f", cTax);
        JTxtTax.setText(taxTotal);
        
        String subtotal = String.format("$ %.2f", cSubtotal);
        JTxtSubtotal.setText(subtotal);
        
        String total = String.format("$ %.2f", cTotal);
        JTxtTotal.setText(total);
    }
    
    public void Change(){
        String temp = JTxtDisplay.getText();
        double sum = 0;
        double cash = Double.parseDouble((temp));
        for(int i = 0; i < jTable1.getRowCount(); i++){
             sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
        }
        double tax = (sum * this.taxRate);
        double change;
        if(cash < sum){
            change = sum + tax - cash;
            String remainingBalance = String.format("$ %.2f", change);
            JTxtDisplay.setText(remainingBalance);
        }
        else{
            change = cash - (sum + tax);
            String changeGiven = String.format("$ %.2f", change);
            jLabelCash.setText("");
            jLabelChange.setText("Change Amt:");
            JTxtDisplay.setText("");
            JTxtChange.setText(changeGiven);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JBtnClear = new javax.swing.JButton();
        JBtn8 = new javax.swing.JButton();
        JBtn9 = new javax.swing.JButton();
        JBtn7 = new javax.swing.JButton();
        JBtn4 = new javax.swing.JButton();
        JBtn5 = new javax.swing.JButton();
        JBtn6 = new javax.swing.JButton();
        JBtn3 = new javax.swing.JButton();
        JBtn2 = new javax.swing.JButton();
        JBtn1 = new javax.swing.JButton();
        JBtn0 = new javax.swing.JButton();
        JBtnDot = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JTxtSubtotal = new javax.swing.JTextField();
        JTxtTax = new javax.swing.JTextField();
        JTxtTotal = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jButtonCalifornia = new javax.swing.JButton();
        jButtonBoston = new javax.swing.JButton();
        jButtonShrimpTem = new javax.swing.JButton();
        jButtonPhiladR = new javax.swing.JButton();
        jButtonYellowtailR = new javax.swing.JButton();
        jButtonSalmonR = new javax.swing.JButton();
        jButtonSpiderR = new javax.swing.JButton();
        jButtonTunaR = new javax.swing.JButton();
        jButtonTokyoR = new javax.swing.JButton();
        jButtonCupidR = new javax.swing.JButton();
        jButtonTNTR = new javax.swing.JButton();
        jButtonDancerR = new javax.swing.JButton();
        jButton111 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonSteakHib = new javax.swing.JButton();
        jButtonCKHib = new javax.swing.JButton();
        jButtonSPHib = new javax.swing.JButton();
        jButtonScalHib = new javax.swing.JButton();
        jButton129 = new javax.swing.JButton();
        jButtonLobHib = new javax.swing.JButton();
        jButtonFiletHib = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        JBtnCrabR = new javax.swing.JButton();
        JBtnEdamame = new javax.swing.JButton();
        JBtnSpringR = new javax.swing.JButton();
        JBtnCalamari = new javax.swing.JButton();
        JBtnGyoza = new javax.swing.JButton();
        JBtnRockCk = new javax.swing.JButton();
        JBtnRockSp = new javax.swing.JButton();
        JBtnAgeTofu = new javax.swing.JButton();
        JBtnSuApp = new javax.swing.JButton();
        JBtnSaApp = new javax.swing.JButton();
        jButton78 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        JBtnExit = new javax.swing.JButton();
        JBtnPay = new javax.swing.JButton();
        JBtnPrint = new javax.swing.JButton();
        JBtnReset = new javax.swing.JButton();
        JBtnRemove = new javax.swing.JButton();
        JTxtChange = new javax.swing.JLabel();
        JTxtDisplay = new javax.swing.JLabel();
        jLabelChange = new javax.swing.JLabel();
        jLabelCash = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtnClear.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnClear.setText("C");
        JBtnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnClearActionPerformed(evt);
            }
        });
        jPanel2.add(JBtnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 70, 70));

        JBtn8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn8.setText("8");
        JBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 70, 70));

        JBtn9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn9.setText("9");
        JBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 70, 70));

        JBtn7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn7.setText("7");
        JBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 70, 70));

        JBtn4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn4.setText("4");
        JBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 70, 70));

        JBtn5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn5.setText("5");
        JBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 70, 70));

        JBtn6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn6.setText("6");
        JBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 70, 70));

        JBtn3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn3.setText("3");
        JBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 70, 70));

        JBtn2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn2.setText("2");
        JBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 70, 70));

        JBtn1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn1.setText("1");
        JBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 70, 70));

        JBtn0.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtn0.setText("0");
        JBtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(JBtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 70));

        JBtnDot.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnDot.setText(".");
        JBtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(JBtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 300, 70, 70));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 730, 330, 400));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Items", "Qty", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, 500, 440));

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("SubTotal");
        jPanel4.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 170, 50));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel2.setText("Tax");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 170, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel3.setText("Total");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 170, 50));

        JTxtSubtotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JTxtSubtotal.setText("00.00");
        jPanel4.add(JTxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 170, 50));

        JTxtTax.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JTxtTax.setText("00.00");
        jPanel4.add(JTxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 80, 170, 50));

        JTxtTotal.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JTxtTotal.setText("00.00");
        jPanel4.add(JTxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 170, 50));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 500, 210));

        jTabbedPane1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCalifornia.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonCalifornia.setText("California Roll");
        jButtonCalifornia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaliforniaActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCalifornia, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 110));

        jButtonBoston.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonBoston.setText("Boston Roll");
        jButtonBoston.setToolTipText("");
        jButtonBoston.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBostonActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonBoston, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 110));

        jButtonShrimpTem.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonShrimpTem.setText("Shrimp Tempura Roll");
        jButtonShrimpTem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShrimpTemActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonShrimpTem, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 110));

        jButtonPhiladR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonPhiladR.setText("Philad Roll");
        jButtonPhiladR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPhiladRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonPhiladR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 120, 110));

        jButtonYellowtailR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonYellowtailR.setText("Yellowtail Roll");
        jButtonYellowtailR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonYellowtailRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonYellowtailR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 120, 110));

        jButtonSalmonR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonSalmonR.setText("Salmon Roll");
        jButtonSalmonR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalmonRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSalmonR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 120, 110));

        jButtonSpiderR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonSpiderR.setText("Spider Roll");
        jButtonSpiderR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSpiderRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonSpiderR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 110));

        jButtonTunaR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonTunaR.setText("Tuna Roll");
        jButtonTunaR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTunaRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonTunaR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, 110));

        jButtonTokyoR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonTokyoR.setText("Tokyo Roll");
        jButtonTokyoR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTokyoRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonTokyoR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 110));

        jButtonCupidR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonCupidR.setText("Cupid Roll");
        jButtonCupidR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCupidRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonCupidR, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 120, 110));

        jButtonTNTR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonTNTR.setText("TNT Roll");
        jButtonTNTR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTNTRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonTNTR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 120, 110));

        jButtonDancerR.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButtonDancerR.setText("Dancer Roll");
        jButtonDancerR.setToolTipText("");
        jButtonDancerR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDancerRActionPerformed(evt);
            }
        });
        jPanel3.add(jButtonDancerR, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, 120, 110));

        jButton111.setFont(new java.awt.Font("Yu Gothic", 0, 12)); // NOI18N
        jButton111.setToolTipText("");
        jPanel3.add(jButton111, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 120, 110));

        jTabbedPane1.addTab("Sushi Rolls", jPanel3);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSteakHib.setText("Steak");
        jButtonSteakHib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSteakHibActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSteakHib, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 110));

        jButtonCKHib.setText("Chicken");
        jButtonCKHib.setToolTipText("");
        jButtonCKHib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCKHibActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonCKHib, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 110));

        jButtonSPHib.setText("Shrimp");
        jButtonSPHib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSPHibActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonSPHib, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 110));

        jButtonScalHib.setText("Scallop");
        jButtonScalHib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonScalHibActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonScalHib, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 120, 110));
        jPanel6.add(jButton129, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 120, 110));

        jButtonLobHib.setText("Lobster");
        jButtonLobHib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLobHibActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonLobHib, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 110));

        jButtonFiletHib.setText("Filet Mignon");
        jButtonFiletHib.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFiletHibActionPerformed(evt);
            }
        });
        jPanel6.add(jButtonFiletHib, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, 110));

        jTabbedPane1.addTab("Hibachi", jPanel6);

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JBtnCrabR.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnCrabR.setText("Crab Ragoon");
        JBtnCrabR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCrabRActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnCrabR, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 120, 110));

        JBtnEdamame.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnEdamame.setText("Edamame");
        JBtnEdamame.setToolTipText("");
        JBtnEdamame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnEdamameActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnEdamame, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 30, 120, 110));

        JBtnSpringR.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnSpringR.setText("Spring Roll");
        JBtnSpringR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSpringRActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnSpringR, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 120, 110));

        JBtnCalamari.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnCalamari.setText("Calamari");
        JBtnCalamari.setToolTipText("");
        JBtnCalamari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnCalamariActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnCalamari, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, 120, 110));

        JBtnGyoza.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnGyoza.setText("Gyoza");
        JBtnGyoza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnGyozaActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnGyoza, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, 120, 110));

        JBtnRockCk.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnRockCk.setText("Rock Chicken");
        JBtnRockCk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRockCkActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnRockCk, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 120, 110));

        JBtnRockSp.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnRockSp.setText("Rock Shrimp");
        JBtnRockSp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRockSpActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnRockSp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 120, 110));

        JBtnAgeTofu.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnAgeTofu.setText("Age Tofu");
        JBtnAgeTofu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnAgeTofuActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnAgeTofu, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 120, 110));

        JBtnSuApp.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnSuApp.setText(" Sushi APP");
        JBtnSuApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSuAppActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnSuApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 120, 110));

        JBtnSaApp.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        JBtnSaApp.setText("Sashimi APP");
        JBtnSaApp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnSaAppActionPerformed(evt);
            }
        });
        jPanel5.add(JBtnSaApp, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 120, 110));

        jButton78.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        jPanel5.add(jButton78, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 120, 110));

        jTextField2.setText("jTextField2");
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 360, -1, -1));

        jTabbedPane1.addTab("Appetizers", jPanel5);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 630, 1090));

        JBtnExit.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnExit.setText("Exit");
        JBtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnExitActionPerformed(evt);
            }
        });
        getContentPane().add(JBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 1070, 140, 60));

        JBtnPay.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnPay.setText("Pay");
        JBtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPayActionPerformed(evt);
            }
        });
        getContentPane().add(JBtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 770, 140, 70));

        JBtnPrint.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnPrint.setText("Print");
        JBtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnPrintActionPerformed(evt);
            }
        });
        getContentPane().add(JBtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 850, 140, 60));

        JBtnReset.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnReset.setText("Reset");
        JBtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnResetActionPerformed(evt);
            }
        });
        getContentPane().add(JBtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 920, 140, 60));

        JBtnRemove.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        JBtnRemove.setText("Remove");
        JBtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnRemoveActionPerformed(evt);
            }
        });
        getContentPane().add(JBtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 990, 140, 70));

        JTxtChange.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        getContentPane().add(JTxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 730, 140, 60));

        JTxtDisplay.setFont(new java.awt.Font("Yu Gothic", 0, 14)); // NOI18N
        getContentPane().add(JTxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 730, 140, 60));

        jLabelChange.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        getContentPane().add(jLabelChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 730, 110, 20));

        jLabelCash.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabelCash.setText("Cash Amt:");
        getContentPane().add(jLabelCash, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 730, 110, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//    private void buttonActionPerformed(java.awt.event.ActionEvent evt){
//        String id = employeeText.getText();
//        String password = passwordText.getText();
//        System.out.println(id + "," + password);
//        status = false;
//        if(id.equals("Nathan") && password.equals("simplepassword")){
//            success.setText("Login Successful!");
//            employeeText.setText("");
//            passwordText.setText("");
//            status = true;
//        }
//        else
//        {
//            success.setText("Wrong login credential, try again");
//            status = false;
//        }
//    }
    private void JBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn8ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn8.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn8.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn8ActionPerformed

    private void JBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn9ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn9.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn9.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn9ActionPerformed

    private void JBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn7ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn7.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn7.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn7ActionPerformed

    private void JBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn4ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn4.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn4.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn4ActionPerformed

    private void JBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn5ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn5.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn5.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn5ActionPerformed

    private void JBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn6ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn5.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn5.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn6ActionPerformed

    private void JBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn3ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn3.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn3.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn3ActionPerformed

    private void JBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn2ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn2.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn2.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn2ActionPerformed

    private void JBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn1ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn1.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn1.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn1ActionPerformed

    private void JBtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtn0ActionPerformed
        // TODO add your handling code here:
        String enterNumber = JTxtDisplay.getText();
        
        if (enterNumber == ""){
            JTxtDisplay.setText(JBtn0.getText());
        }
        else{
            enterNumber = JTxtDisplay.getText() + JBtn0.getText();
            JTxtDisplay.setText(enterNumber);
        }
    }//GEN-LAST:event_JBtn0ActionPerformed

    private void JBtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnDotActionPerformed
        // TODO add your handling code here:
        if(!JTxtDisplay.getText().contains(".")){
            JTxtDisplay.setText(JTxtDisplay.getText() + JBtnDot.getText());
        }
    }//GEN-LAST:event_JBtnDotActionPerformed

    private void JBtnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnClearActionPerformed
        // TODO add your handling code here:
        JTxtDisplay.setText("");
    }//GEN-LAST:event_JBtnClearActionPerformed

    private void JBtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBtnExitActionPerformed

    private void JBtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPayActionPerformed
        // TODO add your handling code here:
        if(!JTxtTotal.getText().equals("00.00")){
            if(!JTxtChange.getText().equals("Change Amt:")){
                Change();
            }
        }
    }//GEN-LAST:event_JBtnPayActionPerformed

    private void JBtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnPrintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Printing in progress");
        MessageFormat footer = new MessageFormat("Page {0, number, intger}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("No printer found", e.getMessage()); 
        }
    }//GEN-LAST:event_JBtnPrintActionPerformed

    private void JBtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnResetActionPerformed
        // TODO add your handling code here:
//        jTable1.setModel(new javax.swing.table.DefaultTableModel(new Object [][] { }, new String [] {"Items", "Qty", "Amount"}));
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        JTxtTotal.setText("00.00");
        JTxtSubtotal.setText("00.00");
        JTxtTax.setText("00.00");
        jLabelChange.setText("");
        jLabelCash.setText("Cash Amt:");
        JTxtDisplay.setText("");
        JTxtChange.setText("");
    }//GEN-LAST:event_JBtnResetActionPerformed

    private void JBtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRemoveActionPerformed
        // TODO add your handling code here:
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        int removedItem = jTable1.getSelectedRow();
        if (removedItem >= 0){
            model.removeRow(removedItem);
        }
        else{
            model.removeRow(model.getRowCount()-1);
        }
        itemCost();
        Change();
    }//GEN-LAST:event_JBtnRemoveActionPerformed

    private void jButtonFiletHibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFiletHibActionPerformed
        // TODO add your handling code here:
        double price = 29.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hibachi Filet Mignon", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonFiletHibActionPerformed

    private void jButtonLobHibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLobHibActionPerformed
        // TODO add your handling code here:
        double price = 31.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hibachi Lobster", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonLobHibActionPerformed

    private void jButtonScalHibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonScalHibActionPerformed
        // TODO add your handling code here:
        double price = 23.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hibachi Scallop", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonScalHibActionPerformed

    private void jButtonSPHibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSPHibActionPerformed
        // TODO add your handling code here:
        double price = 21.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hibachi Shrimp", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonSPHibActionPerformed

    private void jButtonCKHibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCKHibActionPerformed
        // TODO add your handling code here:
        double price = 18.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hibachi Chicken", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonCKHibActionPerformed

    private void jButtonSteakHibActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSteakHibActionPerformed
        // TODO add your handling code here:
        double price = 23.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Hibachi Steak", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonSteakHibActionPerformed

    private void jButtonDancerRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDancerRActionPerformed
        // TODO add your handling code here:
        double price = 16.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Dancer Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonDancerRActionPerformed

    private void jButtonTNTRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTNTRActionPerformed
        // TODO add your handling code here:
        double price = 17.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"TNT Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonTNTRActionPerformed

    private void jButtonCupidRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCupidRActionPerformed
        // TODO add your handling code here:
        double price = 14.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cupid Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonCupidRActionPerformed

    private void jButtonTokyoRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTokyoRActionPerformed
        // TODO add your handling code here:
        double price = 13.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tokyo Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonTokyoRActionPerformed

    private void jButtonTunaRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTunaRActionPerformed
        // TODO add your handling code here:
        double price = 5.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Tuna Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonTunaRActionPerformed

    private void jButtonSpiderRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSpiderRActionPerformed
        // TODO add your handling code here:
        double price = 11.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Spider Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonSpiderRActionPerformed

    private void jButtonSalmonRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalmonRActionPerformed
        // TODO add your handling code here:
        double price = 5.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Salmon Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonSalmonRActionPerformed

    private void jButtonYellowtailRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonYellowtailRActionPerformed
        // TODO add your handling code here:
        double price = 5.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Yellowtail Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonYellowtailRActionPerformed

    private void jButtonPhiladRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPhiladRActionPerformed
        // TODO add your handling code here:
        double price = 7.50;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Philadelphia Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonPhiladRActionPerformed

    private void jButtonShrimpTemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShrimpTemActionPerformed
        // TODO add your handling code here:
        double price = 8.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Shrimp Tempura", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonShrimpTemActionPerformed

    private void jButtonBostonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBostonActionPerformed
        // TODO add your handling code here:
        double price = 6.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Boston Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonBostonActionPerformed

    private void jButtonCaliforniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaliforniaActionPerformed
        // TODO add your handling code here:
        double price = 5.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"California Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_jButtonCaliforniaActionPerformed

    private void JBtnSaAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSaAppActionPerformed
        // TODO add your handling code here:
        double price = 12.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sashimi Appetizer", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnSaAppActionPerformed

    private void JBtnSuAppActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSuAppActionPerformed
        // TODO add your handling code here:
        double price = 11.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Sushi Appetizer", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnSuAppActionPerformed

    private void JBtnAgeTofuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnAgeTofuActionPerformed
        // TODO add your handling code here:
        double price = 6.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Age Tofu", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnAgeTofuActionPerformed

    private void JBtnRockSpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRockSpActionPerformed
        // TODO add your handling code here:
        double price = 11.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rock Shrimp", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnRockSpActionPerformed

    private void JBtnRockCkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnRockCkActionPerformed
        // TODO add your handling code here:
        double price = 10.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Rock Chicken", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnRockCkActionPerformed

    private void JBtnGyozaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnGyozaActionPerformed
        // TODO add your handling code here:
        double price = 7.50;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Gyoza", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnGyozaActionPerformed

    private void JBtnCalamariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCalamariActionPerformed
        // TODO add your handling code here:
        double price = 9.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Calamari", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnCalamariActionPerformed

    private void JBtnSpringRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnSpringRActionPerformed
        // TODO add your handling code here:
        double price = 6.25;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Spring Roll", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnSpringRActionPerformed

    private void JBtnEdamameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnEdamameActionPerformed
        // TODO add your handling code here:
        double price = 5.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Edamame", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnEdamameActionPerformed

    private void JBtnCrabRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnCrabRActionPerformed
        // TODO add your handling code here:
        double price = 5.95;
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Crab Ragoon", "1", price});
        itemCost();
    }//GEN-LAST:event_JBtnCrabRActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
        */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn0;
    private javax.swing.JButton JBtn1;
    private javax.swing.JButton JBtn2;
    private javax.swing.JButton JBtn3;
    private javax.swing.JButton JBtn4;
    private javax.swing.JButton JBtn5;
    private javax.swing.JButton JBtn6;
    private javax.swing.JButton JBtn7;
    private javax.swing.JButton JBtn8;
    private javax.swing.JButton JBtn9;
    private javax.swing.JButton JBtnAgeTofu;
    private javax.swing.JButton JBtnCalamari;
    private javax.swing.JButton JBtnClear;
    private javax.swing.JButton JBtnCrabR;
    private javax.swing.JButton JBtnDot;
    private javax.swing.JButton JBtnEdamame;
    private javax.swing.JButton JBtnExit;
    private javax.swing.JButton JBtnGyoza;
    private javax.swing.JButton JBtnPay;
    private javax.swing.JButton JBtnPrint;
    private javax.swing.JButton JBtnRemove;
    private javax.swing.JButton JBtnReset;
    private javax.swing.JButton JBtnRockCk;
    private javax.swing.JButton JBtnRockSp;
    private javax.swing.JButton JBtnSaApp;
    private javax.swing.JButton JBtnSpringR;
    private javax.swing.JButton JBtnSuApp;
    private javax.swing.JLabel JTxtChange;
    private javax.swing.JLabel JTxtDisplay;
    private javax.swing.JTextField JTxtSubtotal;
    private javax.swing.JTextField JTxtTax;
    private javax.swing.JTextField JTxtTotal;
    private javax.swing.JButton jButton111;
    private javax.swing.JButton jButton129;
    private javax.swing.JButton jButton78;
    private javax.swing.JButton jButtonBoston;
    private javax.swing.JButton jButtonCKHib;
    private javax.swing.JButton jButtonCalifornia;
    private javax.swing.JButton jButtonCupidR;
    private javax.swing.JButton jButtonDancerR;
    private javax.swing.JButton jButtonFiletHib;
    private javax.swing.JButton jButtonLobHib;
    private javax.swing.JButton jButtonPhiladR;
    private javax.swing.JButton jButtonSPHib;
    private javax.swing.JButton jButtonSalmonR;
    private javax.swing.JButton jButtonScalHib;
    private javax.swing.JButton jButtonShrimpTem;
    private javax.swing.JButton jButtonSpiderR;
    private javax.swing.JButton jButtonSteakHib;
    private javax.swing.JButton jButtonTNTR;
    private javax.swing.JButton jButtonTokyoR;
    private javax.swing.JButton jButtonTunaR;
    private javax.swing.JButton jButtonYellowtailR;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelCash;
    private javax.swing.JLabel jLabelChange;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}

